from distutils.core import setup
setup(
  name = 'django-sourdough',
  packages = ['django_sourdough',
              'django_sourdough.fields',
              'django_sourdough.models',
              'django_sourdough.management',
              'django_sourdough.management.commands',
              'django_sourdough.serialisers',
              'django_sourdough.views',
              ],
  version = '0.5',
  description = 'Django tools for fast population and baking',
  author = 'Alex Parsons',
  author_email = 'alex@alexparsons.co.uk',
  url = 'https://github.com/ajparsons/django-sourdough', 
  download_url = '', 
  keywords = ['django'], 
  classifiers = [],
)